configure: Output detection error message if FORCE_SYSTEM_LIBBPF fails
Signed-off-by: Toke Høiland-Jørgensen <toke@redhat.com>

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -44,6 +44,8 @@ check_elf()
 
 check_libbpf()
 {
+    local libbpf_err
+
     if ${PKG_CONFIG} libbpf --exists || [ -n "$LIBBPF_DIR" ]; then
 
         if [ -n "$LIBBPF_DIR" ]; then
@@ -63,7 +65,8 @@ int main(int argc, char **argv) {
 }
 EOF
 
-        if $CC -o $TMPDIR/libbpftest $TMPDIR/libbpftest.c  $LIBBPF_CFLAGS -lbpf >/dev/null 2>&1; then
+        libbpf_err=$($CC -o $TMPDIR/libbpftest $TMPDIR/libbpftest.c  $LIBBPF_CFLAGS -lbpf 2>&1)
+        if [ "$?" -eq "0" ]; then
 	    echo "SYSTEM_LIBBPF:=y" >>$CONFIG
 	    echo 'CFLAGS += ' $LIBBPF_CFLAGS >> $CONFIG
 	    echo 'LDLIBS += ' $LIBBPF_LDLIBS >>$CONFIG
@@ -71,10 +74,13 @@ EOF
 	    echo system
             return 0
         fi
+    else
+        libbpf_err="${PKG_CONFIG} couldn't find libbpf"
     fi
 
     if [ "${FORCE_SYSTEM_LIBBPF:-0}" -eq "1" ]; then
         echo "FORCE_SYSTEM_LIBBPF is set, but no usable libbpf found on system"
+        echo "error: $libbpf_err"
         rm -f "$CONFIG"
         exit 1
     fi
