Makefile: Move llvm-check into configure script
The llvm-check Makefile target didn't actually include the definitions in
config.mk, so in most cases it didn't do anything. And if the CLANG and LLC
variables *were* actually defined in the environment, make would error out
because of missing targets for them.

Since we have a configure script that writes the paths for these tools into
config.mk anyway, really the right place to check for their presence on the
system is there. So just move the check info configure, and get rid of the
llvm-check target entirely.

Signed-off-by: Toke Høiland-Jørgensen <toke@redhat.com>

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -24,6 +24,14 @@ check_toolchain()
     : ${CC=gcc}
     : ${CLANG=clang}
     : ${LLC=llc}
+
+    for TOOL in $PKG_CONFIG $CC $CLANG $LLC; do
+	if [ ! $(command -v ${TOOL} 2>/dev/null) ]; then
+	    echo "*** ERROR: Cannot find tool ${TOOL}" ;
+	    exit 1;
+	fi;
+    done
+
     echo "PKG_CONFIG:=${PKG_CONFIG}" >>$CONFIG
     echo "CC:=${CC}" >>$CONFIG
     echo "CLANG:=${CLANG}" >>$CONFIG
